### ISSUE TITLE
Last update problem!

### ISSUE THREAD

**Issue by F4Jonatas** [poucotm/Guna#38]
After the upgrade I noticed that one of my packages [Inc-Dec-Value](https://packagecontrol.io/packages/Inc-Dec-Value) doesn't work properly, to be more exact, its hotkeys that are not working.

When the Guna package is deactivated, [Inc-Dec-Value](https://packagecontrol.io/packages/Inc-Dec-Value) works normally again.

Is there any possibility to find this glitch and get it fixed?

I currently do not see Sublime without Guna.... ♥

**Comment by poucotm** [comment]
Hi, I'm sorry that, it's because that I added key-maps for color-editing function.
After selecting color code like **fa8019**, try to press the hot-keys.
I think not many people use ctrl+alt+... combination, so I updated key-maps for GunaColorEdit function which I recently added.
Please, check after updating Guna package (v4.1.1) Or you can simply override key-maps : Preferences > Key Bindings.

**Comment by F4Jonatas** [comment]
How wonderful. Everything works perfectly!

For me the best thing was removing the shortcut keys, because I am still using others, like alt+left and alt+right.

Thank you very much!
This Package is a pride.  👏
